training:
  num_steps: 400_000
  batch_size: 32
  gradient_accumulation_steps: 1

dataset:
  root_dir: /workspace/pvc/birds
  image_size: 256
  augment: true

dataloader:
  num_workers: 16
  pin_memory: true
  shuffle: false

optim:
  weight_decay: 0.0001
  lr: 0.0001
  betas: [0.9, 0.999]

checkpointing:
  checkpoint_every: 10_000
  save_dir: /workspace/checkpoints
  generate_every: 10_000