training:
  num_steps: 400_000
  batch_size: 4
  gradient_accumulation_steps: 4

dataset:
  root_dir: /workspace/data/birds
  image_size: 256
  augment: true

dataloader:
  num_workers: 8
  pin_memory: true
  shuffle: true

optim:
  weight_decay: 0.0001
  lr: 0.001
  betas: [0.9, 0.999]

checkpointing:
  checkpoint_every: 10_000
  save_dir: /workspace/checkpoints
  generate_every: 1000